# Generated by Django 5.2.7 on 2025-11-16 20:05

import core.models.user
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('plano', models.CharField(max_length=20)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('cargo', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('passage_id', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(help_text='Email', max_length=255, unique=True, verbose_name='email')),
                ('name', models.CharField(blank=True, help_text='Username', max_length=255, null=True, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, help_text='Indica que este usuário está ativo.', verbose_name='Usuário está ativo')),
                ('is_staff', models.BooleanField(default=False, help_text='Indica que este usuário pode acessar o Admin.', verbose_name='Usuário é da equipe')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', core.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_locacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Locação')),
                ('data_devolucao_prevista', models.DateField(verbose_name='Data de Devolução Prevista')),
                ('data_devolucao_real', models.DateTimeField(blank=True, null=True, verbose_name='Data de Devolução Realizada')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locacoes', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Locação',
                'verbose_name_plural': 'Locações',
                'ordering': ['-data_locacao'],
            },
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ano', models.PositiveIntegerField()),
                ('classificacao_indicativa', models.CharField(max_length=20)),
                ('quantidade', models.PositiveIntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.genero')),
            ],
        ),
        migrations.CreateModel(
            name='LocacaoMidia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.locacao')),
                ('midia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.midia')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_multa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_pagamento', models.DateField(auto_now_add=True)),
                ('metodo', models.CharField(choices=[('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito'), ('pix', 'PIX'), ('dinheiro', 'Dinheiro')], max_length=20)),
                ('locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.locacao')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('midia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.midia')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(max_length=50, verbose_name='ID da Mídia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'media_id')},
            },
        ),
    ]
