# Generated by Django 5.1.7 on 2025-11-28 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_content', 'Novo Conteúdo'), ('favorite_added', 'Adicionado aos Favoritos'), ('recommendation', 'Recomendação'), ('system', 'Sistema'), ('achievement', 'Conquista')], default='system', max_length=20, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadados')),
                ('read', models.BooleanField(default=False, verbose_name='Lida')),
                ('sent_email', models.BooleanField(default=False, verbose_name='Email Enviado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_notifi_user_id_1cc5b6_idx'), models.Index(fields=['user', 'read'], name='core_notifi_user_id_4a178e_idx')],
            },
        ),
    ]
