# Generated by Django 5.2.8 on 2025-11-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_favorite_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favorite',
            name='media_poster_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caminho do Poster'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='media_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Filme'), ('tv', 'Série')], default='movie', max_length=20, verbose_name='Tipo de Mídia'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'media_id', 'media_type')},
        ),
    ]
