# Generated by Django 5.2.7 on 2025-11-07 19:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cliente_funcionario_genero_remove_media_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locacao',
            options={'ordering': ['-data_locacao'], 'verbose_name': 'Locação', 'verbose_name_plural': 'Locações'},
        ),
        migrations.RemoveField(
            model_name='locacao',
            name='data_devolucao',
        ),
        migrations.RemoveField(
            model_name='locacao',
            name='data_prevista_devolucao',
        ),
        migrations.RemoveField(
            model_name='locacao',
            name='data_retirada',
        ),
        migrations.RemoveField(
            model_name='locacao',
            name='status',
        ),
        migrations.AddField(
            model_name='locacao',
            name='data_devolucao_prevista',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Devolução Prevista'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locacao',
            name='data_devolucao_real',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Devolução Realizada'),
        ),
        migrations.AddField(
            model_name='locacao',
            name='data_locacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Locação'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locacoes', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(max_length=50, verbose_name='ID da Mídia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'media_id')},
            },
        ),
    ]
